# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.require_version '>= 1.5.0'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Set the version of chef to install using the vagrant-omnibus plugin
  # NOTE: You will need to install the vagrant-omnibus plugin:
  #
  #   $ vagrant plugin install vagrant-omnibus
  #
  if Vagrant.has_plugin?("vagrant-omnibus")
    config.omnibus.chef_version = 'latest'
  end

  config.vm.network :private_network, ip: "192.168.10.2"

  config.vm.define "master" do |master|
    master.vm.box = 'ubuntu/trusty64'
    master.vm.hostname = 'nps-jenkins-master'
    master.vm.network :forwarded_port, guest: 8080, host: 8080, auto_correct: true

    master.vm.provision :chef_solo do |chef|
      chef.json = {
        mysql: {
          server_root_password: 'rootpass',
          server_debian_password: 'debpass',
          server_repl_password: 'replpass'
        }
      }
      
      chef.run_list = [
                       'recipe[nps-jenkins::master]'
                      ]
    end
  end

  config.vm.define "slave_ubuntu" do |slave_ubuntu|
    slave_ubuntu.vm.box = 'ubuntu/trusty64'
    slave_ubuntu.vm.hostname = 'nps-jenkins-slave-ubuntu'
    slave_ubuntu.vm.network :private_network, ip: "192.168.100.2"

    slave_ubuntu.vm.provision :chef_solo do |chef|
      chef.json = {
        mysql: {
          server_root_password: 'rootpass',
          server_debian_password: 'debpass',
          server_repl_password: 'replpass'
        }
      }
      
      chef.run_list = [
                       'recipe[nps-jenkins::slave]'
                      ]
    end
  end
end
